name: "bitwarden_vault_api"
version: "0.0.1"
description: "OpenAPI API client"
homepage: "homepage"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ">=1.17.0 <2.0.0"
  http: ">=0.13.0 <2.0.0"
  intl: any
  meta: ">=1.1.8 <2.0.0"
dev_dependencies:
  test: ">=1.21.6 <1.22.0"
